Trying:
    porcentajes(0,"Ana está triste y avergonzada")
Expecting:
    Porcentaje de tristeza: 100.0%
    Porcentaje de miedo: 0.0%
    Porcentaje de alegria: 0.0%
    Porcentaje de enfado: 0.0%
    Porcentaje de sorpresa: 0.0%
    Porcentaje de neutral: 0.0%
ok
Trying:
    porcentajes(0,"Llevaba una escopeta")
Expecting:
    Porcentaje de tristeza: 0.0%
    Porcentaje de miedo: 100.0%
    Porcentaje de alegria: 0.0%
    Porcentaje de enfado: 0.0%
    Porcentaje de sorpresa: 0.0%
    Porcentaje de neutral: 0.0%
ok
Trying:
    porcentajes(0,"Estoy alegre y feliz")
Expecting:
    Porcentaje de tristeza: 0.0%
    Porcentaje de miedo: 0.0%
    Porcentaje de alegria: 100.0%
    Porcentaje de enfado: 0.0%
    Porcentaje de sorpresa: 0.0%
    Porcentaje de neutral: 0.0%
ok
Trying:
    porcentajes(0,"Ese tipo es un arrogante")
Expecting:
    Porcentaje de tristeza: 0.0%
    Porcentaje de miedo: 0.0%
    Porcentaje de alegria: 0.0%
    Porcentaje de enfado: 100.0%
    Porcentaje de sorpresa: 0.0%
    Porcentaje de neutral: 0.0%
ok
Trying:
    porcentajes(0,"Me ha sorprendido su actitud")
Expecting:
    Porcentaje de tristeza: 0.0%
    Porcentaje de miedo: 0.0%
    Porcentaje de alegria: 0.0%
    Porcentaje de enfado: 0.0%
    Porcentaje de sorpresa: 100.0%
    Porcentaje de neutral: 0.0%
**********************************************************************
File "test_frase.py", line 37, in __main__.porcentajes
Failed example:
    porcentajes(0,"Me ha sorprendido su actitud")
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
        chunked=chunked)
      File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
        six.raise_from(e, None)
      File "<string>", line 2, in raise_from
      File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
        httplib_response = conn.getresponse()
      File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
        response.begin()
      File "/usr/lib/python3.5/http/client.py", line 297, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
        raise RemoteDisconnected("Remote end closed connection without"
    http.client.RemoteDisconnected: Remote end closed connection without response

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
        timeout=timeout
      File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 357, in increment
        raise six.reraise(type(error), error, _stacktrace)
      File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
        chunked=chunked)
      File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
        six.raise_from(e, None)
      File "<string>", line 2, in raise_from
      File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
        httplib_response = conn.getresponse()
      File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
        response.begin()
      File "/usr/lib/python3.5/http/client.py", line 297, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
        raise RemoteDisconnected("Remote end closed connection without"
    urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.5/doctest.py", line 1321, in __run
        compileflags, 1), test.globs)
      File "<doctest __main__.porcentajes[4]>", line 1, in <module>
        porcentajes(0,"Me ha sorprendido su actitud")
      File "test_frase.py", line 85, in porcentajes
        porcentajes,palabras = interpreta.emociones_frase(frase)
      File "/home/dokrai/Dokrai/TFG-1718-Emociones/Servidor/interprete_frases.py", line 91, in emociones_frase
        porcentajes = interpreta.interpretar_porcentajes(destino) # obtenemos los porcentajes de la palabra
      File "/home/dokrai/Dokrai/TFG-1718-Emociones/Servidor/interprete_palabras.py", line 35, in interpretar_porcentajes
        respuesta = requests.get(destino) # consulta al servicio web
      File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 72, in get
        return request('get', url, params=params, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 58, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 640, in send
        history = [resp for resp in gen] if allow_redirects else []
      File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 640, in <listcomp>
        history = [resp for resp in gen] if allow_redirects else []
      File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 218, in resolve_redirects
        **adapter_kwargs
      File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 490, in send
        raise ConnectionError(err, request=request)
    requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
Trying:
    porcentajes(0,"Pásame un tenedor")
Expecting:
    Porcentaje de tristeza: 0.0%
    Porcentaje de miedo: 0.0%
    Porcentaje de alegria: 0.0%
    Porcentaje de enfado: 0.0%
    Porcentaje de sorpresa: 0.0%
    Porcentaje de neutral: 100.0%
ok
Trying:
    porcentajes(0,"Me voy a dormir")
Expecting:
    Porcentaje de tristeza: 0.0%
    Porcentaje de miedo: 0.0%
    Porcentaje de alegria: 50.0%
    Porcentaje de enfado: 0.0%
    Porcentaje de sorpresa: 0.0%
    Porcentaje de neutral: 50.0%
ok
Trying:
    porcentajes(0,"Ana está triste porque se ha roto su ascensor")
Expecting:
    Porcentaje de tristeza: 55.67%
    Porcentaje de miedo: 0.0%
    Porcentaje de alegria: 0.0%
    Porcentaje de enfado: 11.0%
    Porcentaje de sorpresa: 0.0%
    Porcentaje de neutral: 33.33%
**********************************************************************
File "test_frase.py", line 58, in __main__.porcentajes
Failed example:
    porcentajes(0,"Ana está triste porque se ha roto su ascensor")
Expected:
    Porcentaje de tristeza: 55.67%
    Porcentaje de miedo: 0.0%
    Porcentaje de alegria: 0.0%
    Porcentaje de enfado: 11.0%
    Porcentaje de sorpresa: 0.0%
    Porcentaje de neutral: 33.33%
Got:
    Porcentaje de tristeza: 58.5%
    Porcentaje de miedo: 0.0%
    Porcentaje de alegria: 0.0%
    Porcentaje de enfado: 16.5%
    Porcentaje de sorpresa: 0.0%
    Porcentaje de neutral: 25.0%
Trying:
    porcentajes(1,"Ana está triste y avergonzada")
Expecting:
    La mayoritaria es Tristeza con un 100%
**********************************************************************
File "test_frase.py", line 65, in __main__.porcentajes
Failed example:
    porcentajes(1,"Ana está triste y avergonzada")
Expected:
    La mayoritaria es Tristeza con un 100%
Got:
    La mayoritaria es Tristeza con un 100.0%
Trying:
    porcentajes(1,"Llevaba una escopeta")
Expecting:
    La mayoritaria es Miedo con un 100%
**********************************************************************
File "test_frase.py", line 67, in __main__.porcentajes
Failed example:
    porcentajes(1,"Llevaba una escopeta")
Expected:
    La mayoritaria es Miedo con un 100%
Got:
    La mayoritaria es Miedo con un 100.0%
Trying:
    porcentajes(1,"Mañana es mi boda")
Expecting:
    La mayoritaria es Alegria con un 100%
**********************************************************************
File "test_frase.py", line 69, in __main__.porcentajes
Failed example:
    porcentajes(1,"Mañana es mi boda")
Expected:
    La mayoritaria es Alegria con un 100%
Got:
    La mayoritaria es Alegría con un 100.0%
Trying:
    porcentajes(1,"Ese tipo es un arrogante")
Expecting:
    La mayoritaria es Enfado con un 100%
**********************************************************************
File "test_frase.py", line 71, in __main__.porcentajes
Failed example:
    porcentajes(1,"Ese tipo es un arrogante")
Expected:
    La mayoritaria es Enfado con un 100%
Got:
    La mayoritaria es Enfado con un 100.0%
Trying:
    porcentajes(1,"Me ha sorprendido su actitud")
Expecting:
    La mayoritaria es Sorpresa con un 100%
**********************************************************************
File "test_frase.py", line 73, in __main__.porcentajes
Failed example:
    porcentajes(1,"Me ha sorprendido su actitud")
Expected:
    La mayoritaria es Sorpresa con un 100%
Got:
    La mayoritaria es Sorpresa con un 100.0%
Trying:
    porcentajes(1,"Pásame un tenedor")
Expecting:
    La mayoritaria es Neutral con un 100%
**********************************************************************
File "test_frase.py", line 75, in __main__.porcentajes
Failed example:
    porcentajes(1,"Pásame un tenedor")
Expected:
    La mayoritaria es Neutral con un 100%
Got:
    La mayoritaria es Neutral con un 100.0%
Trying:
    porcentajes(1,"Me voy a dormir")
Expecting:
    La mayoritaria es Hay dos emociones mayoritarias: Alegria y Neutral con un 50%
**********************************************************************
File "test_frase.py", line 77, in __main__.porcentajes
Failed example:
    porcentajes(1,"Me voy a dormir")
Expected:
    La mayoritaria es Hay dos emociones mayoritarias: Alegria y Neutral con un 50%
Got:
    La mayoritaria es Alegría con un 50.0%
Trying:
    porcentajes(1,"Ana está triste porque se ha roto su ascensor")
Expecting:
    La mayoritaria es Tristeza con un 67%
**********************************************************************
File "test_frase.py", line 79, in __main__.porcentajes
Failed example:
    porcentajes(1,"Ana está triste porque se ha roto su ascensor")
Expected:
    La mayoritaria es Tristeza con un 67%
Got:
    La mayoritaria es Tristeza con un 58.5%
1 items had no tests:
    __main__
**********************************************************************
1 items had failures:
  10 of  16 in __main__.porcentajes
16 tests in 2 items.
6 passed and 10 failed.
***Test Failed*** 10 failures.
